import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../../../../../../core/utils/constants/colors/app_colors.dart';
import '../../../controllers/face_detection_controller.dart';
import '../widgets/face_detection_screen/face_action_buttons.dart';
import '../widgets/face_detection_screen/face_image_preview.dart';
import '../widgets/face_detection_screen/face_pdf_button.dart';
import '../widgets/face_detection_screen/face_transform_buttons.dart';

/// Main screen for displaying face detection analysis results.
///
/// [FaceDetectionScreen] presents the face composite image generated by
/// [ImagePreProcessor], along with action buttons for sharing the result,
/// exporting it as a PDF, and navigating back to re-scan a new image.
///
/// This screen is bound to [FaceDetectionController] via
/// [FaceDetectionBinding] and accessed through the `/face-detection` route.
class FaceDetectionScreen extends GetView<FaceDetectionController> {
  /// Creates a [FaceDetectionScreen] widget.
  const FaceDetectionScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.bgPrimary,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios, color: Colors.white, size: 20),
          onPressed: () => Get.back(),
        ),
        title: const Text(
          "Face Analysis Result",
          style: TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.w600),
        ),
        centerTitle: true,
      ),
      body: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 24),
        child: Column(
          children: [
            const SizedBox(height: 10),
            const Expanded(child: FaceImagePreview()),

            const SizedBox(height: 16),

            const FaceTransformButtons(),

            const SizedBox(height: 16),

            const FacePdfButton(),

            const SizedBox(height: 16),

            const FaceActionButtons(),

            const SizedBox(height: 32),
          ],
        ),
      ),
    );
  }
}